# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data_specification_physical_unit_content import DataSpecificationPhysicalUnitContent  # noqa: E501
from swagger_client.rest import ApiException


class TestDataSpecificationPhysicalUnitContent(unittest.TestCase):
    """DataSpecificationPhysicalUnitContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataSpecificationPhysicalUnitContent(self):
        """Test DataSpecificationPhysicalUnitContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data_specification_physical_unit_content.DataSpecificationPhysicalUnitContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
