# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import basyx_server
from basyx_server.models.one_of_data_specification_content import OneOfDataSpecificationContent  # noqa: E501
from basyx_server.rest import ApiException


class TestOneOfDataSpecificationContent(unittest.TestCase):
    """OneOfDataSpecificationContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfDataSpecificationContent(self):
        """Test OneOfDataSpecificationContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = basyx_server.models.one_of_data_specification_content.OneOfDataSpecificationContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
