# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data_specification_iec61360_content import DataSpecificationIEC61360Content  # noqa: E501
from swagger_client.rest import ApiException


class TestDataSpecificationIEC61360Content(unittest.TestCase):
    """DataSpecificationIEC61360Content unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataSpecificationIEC61360Content(self):
        """Test DataSpecificationIEC61360Content"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data_specification_iec61360_content.DataSpecificationIEC61360Content()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
