# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import basyx_server
from basyx_server.models.asset_administration_shell import AssetAdministrationShell  # noqa: E501
from basyx_server.rest import ApiException


class TestAssetAdministrationShell(unittest.TestCase):
    """AssetAdministrationShell unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetAdministrationShell(self):
        """Test AssetAdministrationShell"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.asset_administration_shell.AssetAdministrationShell()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
