# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.referable import Referable  # noqa: F401,E501

class AccessPermissionRule(Referable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'qualifiers': 'list[Constraint]',
        'target_subject_attributes': 'list[SubjectAttributes]',
        'permissions_per_object': 'list[PermissionsPerObject]'
    }
    if hasattr(Referable, "swagger_types"):
        swagger_types.update(Referable.swagger_types)

    attribute_map = {
        'qualifiers': 'qualifiers',
        'target_subject_attributes': 'targetSubjectAttributes',
        'permissions_per_object': 'permissionsPerObject'
    }
    if hasattr(Referable, "attribute_map"):
        attribute_map.update(Referable.attribute_map)

    def __init__(self, qualifiers=None, target_subject_attributes=None, permissions_per_object=None, *args, **kwargs):  # noqa: E501
        """AccessPermissionRule - a model defined in Swagger"""  # noqa: E501
        self._qualifiers = None
        self._target_subject_attributes = None
        self._permissions_per_object = None
        self.discriminator = None
        if qualifiers is not None:
            self.qualifiers = qualifiers
        self.target_subject_attributes = target_subject_attributes
        if permissions_per_object is not None:
            self.permissions_per_object = permissions_per_object
        Referable.__init__(self, *args, **kwargs)

    @property
    def qualifiers(self):
        """Gets the qualifiers of this AccessPermissionRule.  # noqa: E501


        :return: The qualifiers of this AccessPermissionRule.  # noqa: E501
        :rtype: list[Constraint]
        """
        return self._qualifiers

    @qualifiers.setter
    def qualifiers(self, qualifiers):
        """Sets the qualifiers of this AccessPermissionRule.


        :param qualifiers: The qualifiers of this AccessPermissionRule.  # noqa: E501
        :type: list[Constraint]
        """

        self._qualifiers = qualifiers

    @property
    def target_subject_attributes(self):
        """Gets the target_subject_attributes of this AccessPermissionRule.  # noqa: E501


        :return: The target_subject_attributes of this AccessPermissionRule.  # noqa: E501
        :rtype: list[SubjectAttributes]
        """
        return self._target_subject_attributes

    @target_subject_attributes.setter
    def target_subject_attributes(self, target_subject_attributes):
        """Sets the target_subject_attributes of this AccessPermissionRule.


        :param target_subject_attributes: The target_subject_attributes of this AccessPermissionRule.  # noqa: E501
        :type: list[SubjectAttributes]
        """
        if target_subject_attributes is None:
            raise ValueError("Invalid value for `target_subject_attributes`, must not be `None`")  # noqa: E501

        self._target_subject_attributes = target_subject_attributes

    @property
    def permissions_per_object(self):
        """Gets the permissions_per_object of this AccessPermissionRule.  # noqa: E501


        :return: The permissions_per_object of this AccessPermissionRule.  # noqa: E501
        :rtype: list[PermissionsPerObject]
        """
        return self._permissions_per_object

    @permissions_per_object.setter
    def permissions_per_object(self, permissions_per_object):
        """Sets the permissions_per_object of this AccessPermissionRule.


        :param permissions_per_object: The permissions_per_object of this AccessPermissionRule.  # noqa: E501
        :type: list[PermissionsPerObject]
        """

        self._permissions_per_object = permissions_per_object

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccessPermissionRule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessPermissionRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
