# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.identifiable import Identifiable  # noqa: F401,E501

class AssetAdministrationShell(Identifiable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'embedded_data_specifications': 'list[EmbeddedDataSpecification]',
        'derived_from': 'Reference',
        'asset': 'Reference',
        'submodels': 'list[Reference]',
        'views': 'list[View]',
        'concept_dictionaries': 'list[ConceptDictionary]',
        'security': 'Security'
    }
    if hasattr(Identifiable, "swagger_types"):
        swagger_types.update(Identifiable.swagger_types)

    attribute_map = {
        'embedded_data_specifications': 'embeddedDataSpecifications',
        'derived_from': 'derivedFrom',
        'asset': 'asset',
        'submodels': 'submodels',
        'views': 'views',
        'concept_dictionaries': 'conceptDictionaries',
        'security': 'security'
    }
    if hasattr(Identifiable, "attribute_map"):
        attribute_map.update(Identifiable.attribute_map)

    def __init__(self, embedded_data_specifications=None, derived_from=None, asset=None, submodels=None, views=None, concept_dictionaries=None, security=None, *args, **kwargs):  # noqa: E501
        """AssetAdministrationShell - a model defined in Swagger"""  # noqa: E501
        self._embedded_data_specifications = None
        self._derived_from = None
        self._asset = None
        self._submodels = None
        self._views = None
        self._concept_dictionaries = None
        self._security = None
        self.discriminator = None
        if embedded_data_specifications is not None:
            self.embedded_data_specifications = embedded_data_specifications
        if derived_from is not None:
            self.derived_from = derived_from
        self.asset = asset
        if submodels is not None:
            self.submodels = submodels
        if views is not None:
            self.views = views
        if concept_dictionaries is not None:
            self.concept_dictionaries = concept_dictionaries
        if security is not None:
            self.security = security
        Identifiable.__init__(self, *args, **kwargs)

    @property
    def embedded_data_specifications(self):
        """Gets the embedded_data_specifications of this AssetAdministrationShell.  # noqa: E501


        :return: The embedded_data_specifications of this AssetAdministrationShell.  # noqa: E501
        :rtype: list[EmbeddedDataSpecification]
        """
        return self._embedded_data_specifications

    @embedded_data_specifications.setter
    def embedded_data_specifications(self, embedded_data_specifications):
        """Sets the embedded_data_specifications of this AssetAdministrationShell.


        :param embedded_data_specifications: The embedded_data_specifications of this AssetAdministrationShell.  # noqa: E501
        :type: list[EmbeddedDataSpecification]
        """

        self._embedded_data_specifications = embedded_data_specifications

    @property
    def derived_from(self):
        """Gets the derived_from of this AssetAdministrationShell.  # noqa: E501


        :return: The derived_from of this AssetAdministrationShell.  # noqa: E501
        :rtype: Reference
        """
        return self._derived_from

    @derived_from.setter
    def derived_from(self, derived_from):
        """Sets the derived_from of this AssetAdministrationShell.


        :param derived_from: The derived_from of this AssetAdministrationShell.  # noqa: E501
        :type: Reference
        """

        self._derived_from = derived_from

    @property
    def asset(self):
        """Gets the asset of this AssetAdministrationShell.  # noqa: E501


        :return: The asset of this AssetAdministrationShell.  # noqa: E501
        :rtype: Reference
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this AssetAdministrationShell.


        :param asset: The asset of this AssetAdministrationShell.  # noqa: E501
        :type: Reference
        """
        if asset is None:
            raise ValueError("Invalid value for `asset`, must not be `None`")  # noqa: E501

        self._asset = asset

    @property
    def submodels(self):
        """Gets the submodels of this AssetAdministrationShell.  # noqa: E501


        :return: The submodels of this AssetAdministrationShell.  # noqa: E501
        :rtype: list[Reference]
        """
        return self._submodels

    @submodels.setter
    def submodels(self, submodels):
        """Sets the submodels of this AssetAdministrationShell.


        :param submodels: The submodels of this AssetAdministrationShell.  # noqa: E501
        :type: list[Reference]
        """

        self._submodels = submodels

    @property
    def views(self):
        """Gets the views of this AssetAdministrationShell.  # noqa: E501


        :return: The views of this AssetAdministrationShell.  # noqa: E501
        :rtype: list[View]
        """
        return self._views

    @views.setter
    def views(self, views):
        """Sets the views of this AssetAdministrationShell.


        :param views: The views of this AssetAdministrationShell.  # noqa: E501
        :type: list[View]
        """

        self._views = views

    @property
    def concept_dictionaries(self):
        """Gets the concept_dictionaries of this AssetAdministrationShell.  # noqa: E501


        :return: The concept_dictionaries of this AssetAdministrationShell.  # noqa: E501
        :rtype: list[ConceptDictionary]
        """
        return self._concept_dictionaries

    @concept_dictionaries.setter
    def concept_dictionaries(self, concept_dictionaries):
        """Sets the concept_dictionaries of this AssetAdministrationShell.


        :param concept_dictionaries: The concept_dictionaries of this AssetAdministrationShell.  # noqa: E501
        :type: list[ConceptDictionary]
        """

        self._concept_dictionaries = concept_dictionaries

    @property
    def security(self):
        """Gets the security of this AssetAdministrationShell.  # noqa: E501


        :return: The security of this AssetAdministrationShell.  # noqa: E501
        :rtype: Security
        """
        return self._security

    @security.setter
    def security(self, security):
        """Sets the security of this AssetAdministrationShell.


        :param security: The security of this AssetAdministrationShell.  # noqa: E501
        :type: Security
        """

        self._security = security

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssetAdministrationShell, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetAdministrationShell):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
