# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.event import Event  # noqa: F401,E501

class BasicEvent(Event):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'observed': 'Reference'
    }
    if hasattr(Event, "swagger_types"):
        swagger_types.update(Event.swagger_types)

    attribute_map = {
        'observed': 'observed'
    }
    if hasattr(Event, "attribute_map"):
        attribute_map.update(Event.attribute_map)

    def __init__(self, observed=None, *args, **kwargs):  # noqa: E501
        """BasicEvent - a model defined in Swagger"""  # noqa: E501
        self._observed = None
        self.discriminator = None
        self.observed = observed
        Event.__init__(self, *args, **kwargs)

    @property
    def observed(self):
        """Gets the observed of this BasicEvent.  # noqa: E501


        :return: The observed of this BasicEvent.  # noqa: E501
        :rtype: Reference
        """
        return self._observed

    @observed.setter
    def observed(self, observed):
        """Sets the observed of this BasicEvent.


        :param observed: The observed of this BasicEvent.  # noqa: E501
        :type: Reference
        """
        if observed is None:
            raise ValueError("Invalid value for `observed`, must not be `None`")  # noqa: E501

        self._observed = observed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BasicEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BasicEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
