# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.referable import Referable  # noqa: F401,E501

class ConceptDictionary(Referable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'embedded_data_specifications': 'list[EmbeddedDataSpecification]',
        'concept_descriptions': 'list[Reference]'
    }
    if hasattr(Referable, "swagger_types"):
        swagger_types.update(Referable.swagger_types)

    attribute_map = {
        'embedded_data_specifications': 'embeddedDataSpecifications',
        'concept_descriptions': 'conceptDescriptions'
    }
    if hasattr(Referable, "attribute_map"):
        attribute_map.update(Referable.attribute_map)

    def __init__(self, embedded_data_specifications=None, concept_descriptions=None, *args, **kwargs):  # noqa: E501
        """ConceptDictionary - a model defined in Swagger"""  # noqa: E501
        self._embedded_data_specifications = None
        self._concept_descriptions = None
        self.discriminator = None
        if embedded_data_specifications is not None:
            self.embedded_data_specifications = embedded_data_specifications
        if concept_descriptions is not None:
            self.concept_descriptions = concept_descriptions
        Referable.__init__(self, *args, **kwargs)

    @property
    def embedded_data_specifications(self):
        """Gets the embedded_data_specifications of this ConceptDictionary.  # noqa: E501


        :return: The embedded_data_specifications of this ConceptDictionary.  # noqa: E501
        :rtype: list[EmbeddedDataSpecification]
        """
        return self._embedded_data_specifications

    @embedded_data_specifications.setter
    def embedded_data_specifications(self, embedded_data_specifications):
        """Sets the embedded_data_specifications of this ConceptDictionary.


        :param embedded_data_specifications: The embedded_data_specifications of this ConceptDictionary.  # noqa: E501
        :type: list[EmbeddedDataSpecification]
        """

        self._embedded_data_specifications = embedded_data_specifications

    @property
    def concept_descriptions(self):
        """Gets the concept_descriptions of this ConceptDictionary.  # noqa: E501


        :return: The concept_descriptions of this ConceptDictionary.  # noqa: E501
        :rtype: list[Reference]
        """
        return self._concept_descriptions

    @concept_descriptions.setter
    def concept_descriptions(self, concept_descriptions):
        """Sets the concept_descriptions of this ConceptDictionary.


        :param concept_descriptions: The concept_descriptions of this ConceptDictionary.  # noqa: E501
        :type: list[Reference]
        """

        self._concept_descriptions = concept_descriptions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConceptDictionary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConceptDictionary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
