# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.value_object import ValueObject  # noqa: F401,E501

class DataSpecificationIEC61360Content(ValueObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_type': 'str',
        'definition': 'list[LangString]',
        'preferred_name': 'list[LangString]',
        'short_name': 'list[LangString]',
        'source_of_definition': 'str',
        'symbol': 'str',
        'unit': 'str',
        'unit_id': 'Reference',
        'value_format': 'str',
        'value_list': 'ValueList',
        'level_type': 'list[LevelType]'
    }
    if hasattr(ValueObject, "swagger_types"):
        swagger_types.update(ValueObject.swagger_types)

    attribute_map = {
        'data_type': 'dataType',
        'definition': 'definition',
        'preferred_name': 'preferredName',
        'short_name': 'shortName',
        'source_of_definition': 'sourceOfDefinition',
        'symbol': 'symbol',
        'unit': 'unit',
        'unit_id': 'unitId',
        'value_format': 'valueFormat',
        'value_list': 'valueList',
        'level_type': 'levelType'
    }
    if hasattr(ValueObject, "attribute_map"):
        attribute_map.update(ValueObject.attribute_map)

    def __init__(self, data_type=None, definition=None, preferred_name=None, short_name=None, source_of_definition=None, symbol=None, unit=None, unit_id=None, value_format=None, value_list=None, level_type=None, *args, **kwargs):  # noqa: E501
        """DataSpecificationIEC61360Content - a model defined in Swagger"""  # noqa: E501
        self._data_type = None
        self._definition = None
        self._preferred_name = None
        self._short_name = None
        self._source_of_definition = None
        self._symbol = None
        self._unit = None
        self._unit_id = None
        self._value_format = None
        self._value_list = None
        self._level_type = None
        self.discriminator = None
        if data_type is not None:
            self.data_type = data_type
        if definition is not None:
            self.definition = definition
        self.preferred_name = preferred_name
        if short_name is not None:
            self.short_name = short_name
        if source_of_definition is not None:
            self.source_of_definition = source_of_definition
        if symbol is not None:
            self.symbol = symbol
        if unit is not None:
            self.unit = unit
        if unit_id is not None:
            self.unit_id = unit_id
        if value_format is not None:
            self.value_format = value_format
        if value_list is not None:
            self.value_list = value_list
        if level_type is not None:
            self.level_type = level_type
        ValueObject.__init__(self, *args, **kwargs)

    @property
    def data_type(self):
        """Gets the data_type of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The data_type of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this DataSpecificationIEC61360Content.


        :param data_type: The data_type of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: str
        """

        self._data_type = data_type

    @property
    def definition(self):
        """Gets the definition of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The definition of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: list[LangString]
        """
        return self._definition

    @definition.setter
    def definition(self, definition):
        """Sets the definition of this DataSpecificationIEC61360Content.


        :param definition: The definition of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: list[LangString]
        """

        self._definition = definition

    @property
    def preferred_name(self):
        """Gets the preferred_name of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The preferred_name of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: list[LangString]
        """
        return self._preferred_name

    @preferred_name.setter
    def preferred_name(self, preferred_name):
        """Sets the preferred_name of this DataSpecificationIEC61360Content.


        :param preferred_name: The preferred_name of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: list[LangString]
        """
        if preferred_name is None:
            raise ValueError("Invalid value for `preferred_name`, must not be `None`")  # noqa: E501

        self._preferred_name = preferred_name

    @property
    def short_name(self):
        """Gets the short_name of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The short_name of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: list[LangString]
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this DataSpecificationIEC61360Content.


        :param short_name: The short_name of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: list[LangString]
        """

        self._short_name = short_name

    @property
    def source_of_definition(self):
        """Gets the source_of_definition of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The source_of_definition of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: str
        """
        return self._source_of_definition

    @source_of_definition.setter
    def source_of_definition(self, source_of_definition):
        """Sets the source_of_definition of this DataSpecificationIEC61360Content.


        :param source_of_definition: The source_of_definition of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: str
        """

        self._source_of_definition = source_of_definition

    @property
    def symbol(self):
        """Gets the symbol of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The symbol of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this DataSpecificationIEC61360Content.


        :param symbol: The symbol of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def unit(self):
        """Gets the unit of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The unit of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this DataSpecificationIEC61360Content.


        :param unit: The unit of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def unit_id(self):
        """Gets the unit_id of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The unit_id of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: Reference
        """
        return self._unit_id

    @unit_id.setter
    def unit_id(self, unit_id):
        """Sets the unit_id of this DataSpecificationIEC61360Content.


        :param unit_id: The unit_id of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: Reference
        """

        self._unit_id = unit_id

    @property
    def value_format(self):
        """Gets the value_format of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The value_format of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: str
        """
        return self._value_format

    @value_format.setter
    def value_format(self, value_format):
        """Sets the value_format of this DataSpecificationIEC61360Content.


        :param value_format: The value_format of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: str
        """

        self._value_format = value_format

    @property
    def value_list(self):
        """Gets the value_list of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The value_list of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: ValueList
        """
        return self._value_list

    @value_list.setter
    def value_list(self, value_list):
        """Sets the value_list of this DataSpecificationIEC61360Content.


        :param value_list: The value_list of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: ValueList
        """

        self._value_list = value_list

    @property
    def level_type(self):
        """Gets the level_type of this DataSpecificationIEC61360Content.  # noqa: E501


        :return: The level_type of this DataSpecificationIEC61360Content.  # noqa: E501
        :rtype: list[LevelType]
        """
        return self._level_type

    @level_type.setter
    def level_type(self, level_type):
        """Sets the level_type of this DataSpecificationIEC61360Content.


        :param level_type: The level_type of this DataSpecificationIEC61360Content.  # noqa: E501
        :type: list[LevelType]
        """

        self._level_type = level_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataSpecificationIEC61360Content, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataSpecificationIEC61360Content):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
