# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.submodel_element import SubmodelElement  # noqa: F401,E501

class Entity(SubmodelElement):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'statements': 'list[SubmodelElement]',
        'entity_type': 'EntityType',
        'asset': 'Reference'
    }
    if hasattr(SubmodelElement, "swagger_types"):
        swagger_types.update(SubmodelElement.swagger_types)

    attribute_map = {
        'statements': 'statements',
        'entity_type': 'entityType',
        'asset': 'asset'
    }
    if hasattr(SubmodelElement, "attribute_map"):
        attribute_map.update(SubmodelElement.attribute_map)

    def __init__(self, statements=None, entity_type=None, asset=None, *args, **kwargs):  # noqa: E501
        """Entity - a model defined in Swagger"""  # noqa: E501
        self._statements = None
        self._entity_type = None
        self._asset = None
        self.discriminator = None
        if statements is not None:
            self.statements = statements
        self.entity_type = entity_type
        if asset is not None:
            self.asset = asset
        SubmodelElement.__init__(self, *args, **kwargs)

    @property
    def statements(self):
        """Gets the statements of this Entity.  # noqa: E501


        :return: The statements of this Entity.  # noqa: E501
        :rtype: list[SubmodelElement]
        """
        return self._statements

    @statements.setter
    def statements(self, statements):
        """Sets the statements of this Entity.


        :param statements: The statements of this Entity.  # noqa: E501
        :type: list[SubmodelElement]
        """

        self._statements = statements

    @property
    def entity_type(self):
        """Gets the entity_type of this Entity.  # noqa: E501


        :return: The entity_type of this Entity.  # noqa: E501
        :rtype: EntityType
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this Entity.


        :param entity_type: The entity_type of this Entity.  # noqa: E501
        :type: EntityType
        """
        if entity_type is None:
            raise ValueError("Invalid value for `entity_type`, must not be `None`")  # noqa: E501

        self._entity_type = entity_type

    @property
    def asset(self):
        """Gets the asset of this Entity.  # noqa: E501


        :return: The asset of this Entity.  # noqa: E501
        :rtype: Reference
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this Entity.


        :param asset: The asset of this Entity.  # noqa: E501
        :type: Reference
        """

        self._asset = asset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Entity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Entity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
