# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InvocationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_id': 'str',
        'inoutput_arguments': 'list[OperationVariable]',
        'input_arguments': 'list[OperationVariable]',
        'timeout': 'int'
    }

    attribute_map = {
        'request_id': 'requestId',
        'inoutput_arguments': 'inoutputArguments',
        'input_arguments': 'inputArguments',
        'timeout': 'timeout'
    }

    def __init__(self, request_id=None, inoutput_arguments=None, input_arguments=None, timeout=None):  # noqa: E501
        """InvocationRequest - a model defined in Swagger"""  # noqa: E501
        self._request_id = None
        self._inoutput_arguments = None
        self._input_arguments = None
        self._timeout = None
        self.discriminator = None
        if request_id is not None:
            self.request_id = request_id
        if inoutput_arguments is not None:
            self.inoutput_arguments = inoutput_arguments
        if input_arguments is not None:
            self.input_arguments = input_arguments
        if timeout is not None:
            self.timeout = timeout

    @property
    def request_id(self):
        """Gets the request_id of this InvocationRequest.  # noqa: E501


        :return: The request_id of this InvocationRequest.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this InvocationRequest.


        :param request_id: The request_id of this InvocationRequest.  # noqa: E501
        :type: str
        """

        self._request_id = request_id

    @property
    def inoutput_arguments(self):
        """Gets the inoutput_arguments of this InvocationRequest.  # noqa: E501


        :return: The inoutput_arguments of this InvocationRequest.  # noqa: E501
        :rtype: list[OperationVariable]
        """
        return self._inoutput_arguments

    @inoutput_arguments.setter
    def inoutput_arguments(self, inoutput_arguments):
        """Sets the inoutput_arguments of this InvocationRequest.


        :param inoutput_arguments: The inoutput_arguments of this InvocationRequest.  # noqa: E501
        :type: list[OperationVariable]
        """

        self._inoutput_arguments = inoutput_arguments

    @property
    def input_arguments(self):
        """Gets the input_arguments of this InvocationRequest.  # noqa: E501


        :return: The input_arguments of this InvocationRequest.  # noqa: E501
        :rtype: list[OperationVariable]
        """
        return self._input_arguments

    @input_arguments.setter
    def input_arguments(self, input_arguments):
        """Sets the input_arguments of this InvocationRequest.


        :param input_arguments: The input_arguments of this InvocationRequest.  # noqa: E501
        :type: list[OperationVariable]
        """

        self._input_arguments = input_arguments

    @property
    def timeout(self):
        """Gets the timeout of this InvocationRequest.  # noqa: E501


        :return: The timeout of this InvocationRequest.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this InvocationRequest.


        :param timeout: The timeout of this InvocationRequest.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvocationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvocationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
