# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Key(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'KeyElements',
        'id_type': 'KeyType',
        'value': 'str',
        'local': 'bool'
    }

    attribute_map = {
        'type': 'type',
        'id_type': 'idType',
        'value': 'value',
        'local': 'local'
    }

    def __init__(self, type=None, id_type=None, value=None, local=None):  # noqa: E501
        """Key - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._id_type = None
        self._value = None
        self._local = None
        self.discriminator = None
        self.type = type
        self.id_type = id_type
        self.value = value
        self.local = local

    @property
    def type(self):
        """Gets the type of this Key.  # noqa: E501


        :return: The type of this Key.  # noqa: E501
        :rtype: KeyElements
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Key.


        :param type: The type of this Key.  # noqa: E501
        :type: KeyElements
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def id_type(self):
        """Gets the id_type of this Key.  # noqa: E501


        :return: The id_type of this Key.  # noqa: E501
        :rtype: KeyType
        """
        return self._id_type

    @id_type.setter
    def id_type(self, id_type):
        """Sets the id_type of this Key.


        :param id_type: The id_type of this Key.  # noqa: E501
        :type: KeyType
        """
        if id_type is None:
            raise ValueError("Invalid value for `id_type`, must not be `None`")  # noqa: E501

        self._id_type = id_type

    @property
    def value(self):
        """Gets the value of this Key.  # noqa: E501


        :return: The value of this Key.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Key.


        :param value: The value of this Key.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def local(self):
        """Gets the local of this Key.  # noqa: E501


        :return: The local of this Key.  # noqa: E501
        :rtype: bool
        """
        return self._local

    @local.setter
    def local(self, local):
        """Sets the local of this Key.


        :param local: The local of this Key.  # noqa: E501
        :type: bool
        """
        if local is None:
            raise ValueError("Invalid value for `local`, must not be `None`")  # noqa: E501

        self._local = local

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Key, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Key):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
