# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.submodel_element import SubmodelElement  # noqa: F401,E501

class SubmodelElementCollection(SubmodelElement):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value': 'list[object]',
        'allow_duplicates': 'bool',
        'ordered': 'bool'
    }
    if hasattr(SubmodelElement, "swagger_types"):
        swagger_types.update(SubmodelElement.swagger_types)

    attribute_map = {
        'value': 'value',
        'allow_duplicates': 'allowDuplicates',
        'ordered': 'ordered'
    }
    if hasattr(SubmodelElement, "attribute_map"):
        attribute_map.update(SubmodelElement.attribute_map)

    def __init__(self, value=None, allow_duplicates=None, ordered=None, *args, **kwargs):  # noqa: E501
        """SubmodelElementCollection - a model defined in Swagger"""  # noqa: E501
        self._value = None
        self._allow_duplicates = None
        self._ordered = None
        self.discriminator = None
        if value is not None:
            self.value = value
        if allow_duplicates is not None:
            self.allow_duplicates = allow_duplicates
        if ordered is not None:
            self.ordered = ordered
        SubmodelElement.__init__(self, *args, **kwargs)

    @property
    def value(self):
        """Gets the value of this SubmodelElementCollection.  # noqa: E501


        :return: The value of this SubmodelElementCollection.  # noqa: E501
        :rtype: list[object]
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SubmodelElementCollection.


        :param value: The value of this SubmodelElementCollection.  # noqa: E501
        :type: list[object]
        """

        self._value = value

    @property
    def allow_duplicates(self):
        """Gets the allow_duplicates of this SubmodelElementCollection.  # noqa: E501


        :return: The allow_duplicates of this SubmodelElementCollection.  # noqa: E501
        :rtype: bool
        """
        return self._allow_duplicates

    @allow_duplicates.setter
    def allow_duplicates(self, allow_duplicates):
        """Sets the allow_duplicates of this SubmodelElementCollection.


        :param allow_duplicates: The allow_duplicates of this SubmodelElementCollection.  # noqa: E501
        :type: bool
        """

        self._allow_duplicates = allow_duplicates

    @property
    def ordered(self):
        """Gets the ordered of this SubmodelElementCollection.  # noqa: E501


        :return: The ordered of this SubmodelElementCollection.  # noqa: E501
        :rtype: bool
        """
        return self._ordered

    @ordered.setter
    def ordered(self, ordered):
        """Sets the ordered of this SubmodelElementCollection.


        :param ordered: The ordered of this SubmodelElementCollection.  # noqa: E501
        :type: bool
        """

        self._ordered = ordered

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubmodelElementCollection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmodelElementCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
