# coding: utf-8

"""
    BaSyx Asset Administration Shell Repository HTTP REST-API

    The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API  # noqa: E501

    OpenAPI spec version: v1
    Contact: constantin.ziesche@bosch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from basyx_server.models.referable import Referable  # noqa: F401,E501

class View(Referable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'embedded_data_specifications': 'list[EmbeddedDataSpecification]',
        'semantic_id': 'Reference',
        'contained_elements': 'list[Reference]'
    }
    if hasattr(Referable, "swagger_types"):
        swagger_types.update(Referable.swagger_types)

    attribute_map = {
        'embedded_data_specifications': 'embeddedDataSpecifications',
        'semantic_id': 'semanticId',
        'contained_elements': 'containedElements'
    }
    if hasattr(Referable, "attribute_map"):
        attribute_map.update(Referable.attribute_map)

    def __init__(self, embedded_data_specifications=None, semantic_id=None, contained_elements=None, *args, **kwargs):  # noqa: E501
        """View - a model defined in Swagger"""  # noqa: E501
        self._embedded_data_specifications = None
        self._semantic_id = None
        self._contained_elements = None
        self.discriminator = None
        if embedded_data_specifications is not None:
            self.embedded_data_specifications = embedded_data_specifications
        if semantic_id is not None:
            self.semantic_id = semantic_id
        if contained_elements is not None:
            self.contained_elements = contained_elements
        Referable.__init__(self, *args, **kwargs)

    @property
    def embedded_data_specifications(self):
        """Gets the embedded_data_specifications of this View.  # noqa: E501


        :return: The embedded_data_specifications of this View.  # noqa: E501
        :rtype: list[EmbeddedDataSpecification]
        """
        return self._embedded_data_specifications

    @embedded_data_specifications.setter
    def embedded_data_specifications(self, embedded_data_specifications):
        """Sets the embedded_data_specifications of this View.


        :param embedded_data_specifications: The embedded_data_specifications of this View.  # noqa: E501
        :type: list[EmbeddedDataSpecification]
        """

        self._embedded_data_specifications = embedded_data_specifications

    @property
    def semantic_id(self):
        """Gets the semantic_id of this View.  # noqa: E501


        :return: The semantic_id of this View.  # noqa: E501
        :rtype: Reference
        """
        return self._semantic_id

    @semantic_id.setter
    def semantic_id(self, semantic_id):
        """Sets the semantic_id of this View.


        :param semantic_id: The semantic_id of this View.  # noqa: E501
        :type: Reference
        """

        self._semantic_id = semantic_id

    @property
    def contained_elements(self):
        """Gets the contained_elements of this View.  # noqa: E501


        :return: The contained_elements of this View.  # noqa: E501
        :rtype: list[Reference]
        """
        return self._contained_elements

    @contained_elements.setter
    def contained_elements(self, contained_elements):
        """Sets the contained_elements of this View.


        :param contained_elements: The contained_elements of this View.  # noqa: E501
        :type: list[Reference]
        """

        self._contained_elements = contained_elements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(View, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, View):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
